### ISSUE TITLE
Need to logout/disconnect

### ISSUE THREAD

**Issue by larrytech7** [mnkgrover08/codeigniter_social_login#1]
We need functoinality to logout when connected via the social login. Functionality or method to logout from the social login in missing

**Comment by mnkgrover08** [comment]
Logout is a simple mechanism for clearing cookies and session. It was not mentioned because everybody uses their own custom cookie names and custom logic. However for your convenience  I am sharing a logout function that you may use for clearing social sessions and custom uname/pass login.
  
        public function logout() {
		$this->Cookie->delete(<YOUR_LOGIN_COOKIE_NAME>);
		$this->clearSession();
		$this->redirect(<YOUR_LOGOUT_REDIRECT_URL>);
        }

        private function clearSession() {
		$this->session->delete("fb_".<YOUR_FB_APP_ID>."_code");
		$this->session->delete("fb_".<YOUR_FB_APP_ID>."_access_token");
		$this->session->delete("fb_".<YOUR_FB_APP_ID>."_user_id");
		$this->session->delete("ot");
		$this->session->delete("ots");
		$this->session->delete("oauth.linkedin");
		$this->session->delete("fs_access_token");
		$this->session->delete("G_token");
        }
